#!/usr/bin/env python3
"""Tests for the ResearchBrief structured input (optimization priority 1)."""

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "engine"))

from research_brief import (
    AblationSpec,
    BaselineSpec,
    Hypothesis,
    MetricSpec,
    ResearchBrief,
    ResearchTask,
    SectionSpec,
    infer_role,
)


class TestNormalization:
    def test_plain_strings_become_specs(self):
        brief = ResearchBrief(
            baselines=["TGN", "GAT"],
            ablation_dims=["w/o Duration"],
            metrics=["MRR", "Hits@10"],
        )
        assert all(isinstance(b, BaselineSpec) for b in brief.baselines)
        assert all(isinstance(a, AblationSpec) for a in brief.ablation_dims)
        assert all(isinstance(m, MetricSpec) for m in brief.metrics)
        assert brief.baselines[0].name == "TGN"

    def test_dict_items_become_specs(self):
        brief = ResearchBrief(
            baselines=[{"name": "TGN", "category": "temporal-gnn"}],
            hypotheses=[{"statement": "X predicts Y", "rationale": "prior work"}],
        )
        assert brief.baselines[0].category == "temporal-gnn"
        assert brief.hypotheses[0].rationale == "prior work"

    def test_hypothesis_and_task_ids_autogenerated(self):
        brief = ResearchBrief(
            hypotheses=[Hypothesis(statement="a"), Hypothesis(statement="b")],
            tasks=[ResearchTask(name="Recognition")],
        )
        assert [h.id for h in brief.hypotheses] == ["H1", "H2"]
        assert brief.tasks[0].id == "T1"

    def test_invalid_item_type_raises(self):
        with pytest.raises(ValueError):
            ResearchBrief(baselines=[42])


class TestFromDict:
    def test_aliases_negative_claims(self):
        brief = ResearchBrief.from_dict({"negative_claims": ["claim A"]})
        assert brief.forbidden_claims == ["claim A"]

    def test_aliases_custom_outline(self):
        brief = ResearchBrief.from_dict({"custom_outline": [{"title": "Intro"}]})
        assert len(brief.output_sections) == 1
        assert brief.output_sections[0].title == "Intro"

    def test_aliases_search_questions(self):
        brief = ResearchBrief.from_dict({"search_questions": ["q1"]})
        assert brief.literature_search_questions == ["q1"]

    def test_unknown_keys_warn_not_fail(self):
        brief = ResearchBrief.from_dict({"title": "T", "bogus_field": 1})
        assert brief.title == "T"

    def test_roundtrip(self):
        brief = ResearchBrief(
            title="T",
            research_questions=["RQ1: x"],
            baselines=[BaselineSpec(name="TGN")],
            metrics=[MetricSpec(name="Hits@K", k_value=10, priority="primary")],
            forbidden_claims=["no causal claims"],
        )
        restored = ResearchBrief.from_dict(brief.to_dict())
        assert restored.title == "T"
        assert restored.metrics[0].k_value == 10
        assert restored.forbidden_claims == ["no causal claims"]


class TestFileLoading:
    def test_from_yaml(self, tmp_path):
        yaml_content = """
title: Test Paper
research_questions:
  - RQ1: something
baselines:
  - name: TGN
    category: temporal-gnn
metrics:
  - name: MRR
"""
        p = tmp_path / "brief.yaml"
        p.write_text(yaml_content, encoding="utf-8")
        brief = ResearchBrief.from_yaml(p)
        assert brief.title == "Test Paper"
        assert brief.baselines[0].name == "TGN"

    def test_from_json(self, tmp_path):
        p = tmp_path / "brief.json"
        p.write_text(json.dumps({"title": "J", "venue_target": "WWW"}), encoding="utf-8")
        brief = ResearchBrief.from_file(p)
        assert brief.venue_target == "WWW"

    def test_unsupported_extension(self, tmp_path):
        p = tmp_path / "brief.txt"
        p.write_text("title: x", encoding="utf-8")
        with pytest.raises(ValueError):
            ResearchBrief.from_file(p)


class TestPromptContext:
    def test_empty_brief_renders_empty(self):
        assert ResearchBrief().to_prompt_context() == ""
        assert ResearchBrief().is_empty()

    def test_full_brief_renders_all_sections(self):
        brief = ResearchBrief(
            core_question="Why X?",
            research_questions=["RQ1: a"],
            hypotheses=[Hypothesis(id="H1", statement="s")],
            tasks=[ResearchTask(id="T1", name="Rec")],
            innovations=["novel fusion"],
            baselines=[BaselineSpec(name="TGN")],
            ablation_dims=[AblationSpec(name="w/o Duration", dimension="duration")],
            metrics=[MetricSpec(name="Hits@K", k_value=10, priority="primary")],
            split_strategy="temporal",
            ground_truth_protocol="check-ins",
            forbidden_claims=["no causal claims"],
            venue_target="ICWSM",
            output_sections=[SectionSpec(title="Eval", role="results", target_words=1000)],
            additional_context="extra",
        )
        text = brief.to_prompt_context()
        for expected in [
            "RESEARCH BRIEF",
            "Why X?",
            "RQ1: a",
            "H1: s",
            "T1: Rec",
            "novel fusion",
            "TGN",
            "w/o Duration",
            "Hits@K (K=10) [primary]",
            "temporal",
            "check-ins",
            "FORBIDDEN",
            "ICWSM",
            "Eval",
            "extra",
        ]:
            assert expected in text, f"missing: {expected}"

    def test_rich_brief_not_empty(self):
        assert not ResearchBrief(core_question="q").is_empty()


class TestRoles:
    def test_infer_role(self):
        assert infer_role("Related Work") == "literature_review"
        assert infer_role("System Design and Implementation") == "methodology"
        assert infer_role("Evaluation") == "results"
        assert infer_role("Threat Model") is None

    def test_post_init_infers_roles(self):
        brief = ResearchBrief(
            output_sections=[
                {"title": "Introduction"},
                {"title": "Experiments"},
                {"title": "Threat Model"},
            ]
        )
        roles = [s.role for s in brief.output_sections]
        assert roles[0] == "introduction"
        assert roles[1] == "results"
        assert roles[2] is None  # custom section


class TestEffectiveTopic:
    def test_title_wins_over_core_question(self):
        brief = ResearchBrief(title="A", core_question="B")
        assert brief.effective_topic == "A"

    def test_core_question_fallback(self):
        assert ResearchBrief(core_question="B").effective_topic == "B"

    def test_none_when_both_missing(self):
        assert ResearchBrief().effective_topic is None
